name: Storybook

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize

jobs:
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.11.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build:storybook
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: storybook-files
          path: docs

  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: build-storybook
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: storybook-files
          path: docs
      - name: Set branch environment variables
        if: github.event_name != 'pull_request'
        run: |
          echo "::set-env name=TARGET_DIR::${GITHUB_REF##*/}"
      - name: Set PR environment variables
        if: github.event_name == 'pull_request'
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
        run: |
          echo "::set-env name=TARGET_DIR::pull/${PULL_REQUEST_NUMBER}"
      - name: Commit updates
        run: |
          mkdir -p storybook/${TARGET_DIR}
          rm -rf storybook/${TARGET_DIR}
          mv docs storybook/${TARGET_DIR}
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git pull --no-edit --quiet
          git commit -m "Deploy storybook for ${TARGET_DIR}."
          git push origin gh-pages
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}

  remove-storybook:
    name: Remove Storybook
    runs-on: ubuntu-latest
    if: ( github.event_name == 'pull_request' && github.event.action == 'closed' ) && github.event.pull_request.head.repo.fork == false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Remove storybook
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
        run: |
          git rm -rf storybook/pull/${PULL_REQUEST_NUMBER}
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git pull --no-edit --quiet
          git commit -m "Remove storybook for pull/${PULL_REQUEST_NUMBER}."
          git push origin gh-pages